### ISSUE TITLE
Podobne ClaroRead - mozna inspirace na vylepseni

### ISSUE THREAD

**Issue by maper64** [actum/text-spacing-editor#19]
Pěkné, funkční, myslím, že poslouží hlavně dyslektikům.
Podobné funkce v programu ClaroRead - také plugin pro Chrome, ale tam rozpal znaků už není, možná byl, nyní jiné funkce.
Ale rozpal znaků, mezer mezi slovy, řádků a odstavců je (pokud to bylo zachováno) v placené verzi ClaroReadu pro MS Office (Word).
Tam je ještě zajímavá věc, která se dle mého může hodit dyslektikům a to zastínění okolního textu a třeba o ní rozšíříte jednou i svůj addons.
Buď zobrazení jen jednoho znaku v okýnku, nebo slova - to je už praktičtější, nebo jednoho řádku a zvýraznění čteného slova rámečkem a nebo zvýraznění celého čteného odstavce a čtených slov v odstavci.
Čtený = ClaroRead je propojen s TTS (Text to speech) a teď vidím, že umí v addons i STT (speech to text).
K Vašemu addons jsem se dostal prostřednictvím YT kanálu Bez bariér, jsem těžce slabozraký.
Ještě možná jedna důležitá informace - Váš addons Editor rozložení textu funguje velmi dobře i s čtecím nástrojem ZoomTextu AppReader - ZoomText - zvětšovacího SW s podporou hlasu. S dalšími screen readery jsem zatím nezkoušel, ale domnívám se, že to bude taky v pořádku.
Přeji hodně úspěchů v další práci v přístupnosti i ve vývoji tohoto addons.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by zmrhaljiri** [comment]
@maper64, moc děkuji za feedback. Těší mě, že rozšíření někdo používá a že je užitečné.

Koukal jsem na ClaroRead a jeho funkce jsou opravdu nad rámec našeho rozšíření - editor rozložení textu by měl dělat jen tu jednu věc. Můžeme přidat funkce, které uživatelům usnadní jeho používání, ale přidávat věci o kterých píšete, byť jsou rozhodně velmi užitečné pro uživatele, neplánujeme, toto rozšíření je jednoúčelové.

Na druhou stranu - pohrával jsem si s myšlenkou udělat časem další rozšíření, které by mělo více funkcí, podobně jako to má [Helperbird](https://www.helperbird.com/).

**Comment by maper64** [comment]
Dobrý den, Jiří,
také děkuji za reakci. Asi by to chtělo zeptat se přímo odborníků na
dyslexii, jestli jim stačí, když se zvětší mezery mezi znaky, slovy,
odstavci. Pro nás slabozraké to určitou roli hraje myslím v případě volby
písma - změna na Arial, bezpatkové a možná řádky - ideální, když nám
asistivní software ukazuje, kde čte - ale to je už o tom, že uživatel má
své asistivní vybavení a Váš plugin - rozšíření jako doplněk.
Hodně úspěchů do nového roku. Miloš

út 2. 1. 2024 v 10:46 odesílatel Jiří ***@***.***> napsal:
